### ISSUE TITLE
feature: cloudbuildがnameの設定で落ちてるみたいだったので修正したい

### ISSUE THREAD

**Issue by mamepon2580** [waiwai-developers/waiwaichan#261]
- #260

**Comment by mamepon2580** [comment]
<img width="1678" alt="スクリーンショット 2024-11-24 15 34 19" src="https://github.com/user-attachments/assets/38117031-6c13-4bce-a4bb-0840f069f169">

**Comment by mamepon2580** [comment]
以下のnameは任意ではなく指定されたnameを使用する必要があったので変更しました！
```
steps:
  - name: 'image build' to gcr.io/cloud-builders/docker
  - name: 'image push' to gcr.io/cloud-builders/docker
  - name: 'deploy instance' to  name: 'google/cloud-sdk'
```
