### ISSUE TITLE
feature: deployの切り戻し用のscriptを作りたい

### ISSUE THREAD

**Issue by mamepone** [waiwai-developers/waiwaichan#280]

**Comment by mamepon2580** [comment]
切り戻し用のscript([commit id]を置き変える)
```bash
        gcloud compute ssh waiwaichan-server --zone=asia-northeast1-a --command="
          cd /app/waiwaichan && \
          git config --global --add safe.directory /app/waiwaichan && \
          sudo git pull origin main && \
          sudo docker compose -f ./environment/production/docker-compose.yml down && \
          sudo docker container prune -f && \
          sudo docker image prune -f && \
          gcloud auth activate-service-account --key-file=config/key.json && \
          cat config/key.json | docker login -u _json_key --password-stdin asia-northeast1-docker.pkg.dev && \
          sudo docker pull asia-northeast1-docker.pkg.dev/waiwai-406106/waiwaichan/image:[commit id]&& \
          sudo docker compose -f ./environment/production/docker-compose.yml pull && \
          sudo docker compose -f ./environment/production/docker-compose.yml up -d
        "
```

**Comment by mamepon2580** [comment]
script
```
gcloud compute ssh waiwaichan-server --zone=asia-northeast1-a --command="
  commitId=1234567 && \
  cd /app/waiwaichan && \
cat > docker-compose.yml << EOF
services:
  backend:
    container_name: waiwai-backend
    restart: always
    tty: true
    image: asia-northeast1-docker.pkg.dev/waiwai-406106/waiwaichan/image:${commitId}
    volumes:
      - type: bind
        source: ../../config
        target: /app/config
      - type: volume
        source: backend_node_modules
        target: /app/node_modules
    networks:
      - server-network
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: config/key.json
    command: sh -c "npm i && pnpm run dev"
  scheduler:
    container_name: waiwai-scheduler
    restart: "always"
    image: asia-northeast1-docker.pkg.dev/waiwai-406106/waiwaichan/image:${commitId}
    volumes:
      - type: bind
        source: ../../config
        target: /app/config
      - type: volume
        source: scheduler_node_modules
        target: /app/node_modules
    networks:
      - server-network
    command: sh -c "npm i && pnpm run dev:scheduler"
  migrate:
    container_name: waiwai-migrate
    restart: "no"
    image: asia-northeast1-docker.pkg.dev/waiwai-406106/waiwaichan/image:${commitId}
    volumes:
      - type: bind
        source: ../../config
        target: /app/config
      - type: volume
        source: migrate_node_modules
        target: /app/node_modules
    networks:
      - server-network
    command: sh -c "npm i && pnpm run migrate up && pnpm run seed up"
networks:
  server-network:
    driver: bridge
volumes:
  backend_node_modules:
  scheduler_node_modules:
  migrate_node_modules:
EOF && \
  git config --global --add safe.directory /app/waiwaichan && \
  sudo git pull origin main && \
  sudo docker compose -f ./environment/production/docker-compose.yml down && \
  sudo docker container prune -f && \
  sudo docker image prune -f && \
  gcloud auth activate-service-account --key-file=config/key.json && \
  cat config/key.json | docker login -u _json_key --password-stdin asia-northeast1-docker.pkg.dev && \
  sudo docker pull asia-northeast1-docker.pkg.dev/waiwai-406106/waiwaichan/image:$commitId && \
  sudo docker compose -f ./environment/production/docker-compose.yml pull && \
  sudo docker compose -f ./environment/production/docker-compose.yml up -d
"
```
